import { format } from 'date-fns'
import { CATEGORIES, categoryLabel } from './categories'
import { CONDITION_LABELS } from './labels'
import { appConfig } from '../lib/config'

const round = (n) => Math.round(n * 100) / 100
const pct = (part, whole) => (whole ? round((part / whole) * 100) : 0)
const dt = (iso) => (iso ? format(new Date(iso), 'dd-MMM-yyyy HH:mm') : '')

/**
 * Builds the report workbook client-side with SheetJS (loaded on demand so it
 * doesn't weigh down the main bundle). Strings are written as text cells, so
 * values from the database can never be interpreted as formulas.
 */
export async function exportReportToExcel(data, shipments, meta) {
  const XLSX = await import('xlsx')
  const wb = XLSX.utils.book_new()

  const addSheet = (name, rows, widths) => {
    const ws = XLSX.utils.aoa_to_sheet(rows)
    ws['!cols'] = widths.map((wch) => ({ wch }))
    XLSX.utils.book_append_sheet(wb, ws, name)
  }

  const avg = data.shipments ? round(data.totalKg / data.shipments) : 0
  addSheet(
    'Summary',
    [
      [`${appConfig.appName} — Donation Report`],
      [appConfig.office],
      [],
      ['Report type', meta.periodType],
      ['Period', meta.periodLabel],
      ...meta.filterLines.map((line, i) => [i === 0 ? 'Filters' : '', line]),
      ['Generated', format(new Date(), 'dd-MMM-yyyy HH:mm')],
      ['Generated by', meta.generatedBy],
      [],
      ['What', 'Number'],
      ['Total weight (kg)', round(data.totalKg)],
      ['Shipments sent', data.shipments],
      ['Received', data.receivedShipments],
      ['On the way', Math.max(0, data.shipments - data.receivedShipments)],
      ['Average per shipment (kg)', avg],
    ],
    [28, 48],
  )

  addSheet(
    'By item',
    [
      ['Item', 'Weight (kg)', 'Part (%)'],
      ...CATEGORIES.map((c) => {
        const kg = data.byCategory.find((r) => r.category === c.key)?.total_kg ?? 0
        return [c.label, round(kg), pct(kg, data.totalKg)]
      }),
      ['Total', round(data.totalKg), data.totalKg ? 100 : 0],
    ],
    [16, 14, 12],
  )

  const locationSheet = (rows) => [
    ['Code', 'Name', 'Shipments', 'Weight (kg)', 'Part (%)'],
    ...rows.map((r) => [r.short_code ?? '', r.name, r.shipments, round(r.total_kg), pct(r.total_kg, data.totalKg)]),
  ]
  addSheet('By collection point', locationSheet(data.byCollectionPoint), [12, 40, 12, 14, 12])
  addSheet('By distribution center', locationSheet(data.byDistributionCenter), [12, 40, 12, 14, 12])

  addSheet(
    'Each period',
    [
      ['Period', ...CATEGORIES.map((c) => `${c.label} (kg)`), 'Total (kg)'],
      ...data.trend.map((t) => [t.longLabel, ...CATEGORIES.map((c) => round(t[c.key])), round(t.total)]),
    ],
    [18, ...CATEGORIES.map(() => 14), 14],
  )

  addSheet(
    'Shipments',
    [
      [
        'Shipment No.',
        'Collection point',
        'Distribution center',
        'Sent on',
        'Received on',
        'Status',
        'Condition',
        ...CATEGORIES.map((c) => `${categoryLabel(c.key)} (kg)`),
        'Other (what it was)',
        'Total (kg)',
        'Driver / carried by',
        'Vehicle',
      ],
      ...shipments.map((s) => [
        s.batch_code ?? '',
        s.collection_point?.name ?? '',
        s.distribution_center?.name ?? '',
        dt(s.dispatched_at),
        dt(s.received_at),
        s.status === 'received' ? 'Received' : 'On the way',
        s.condition ? (CONDITION_LABELS[s.condition] ?? s.condition) : '',
        ...CATEGORIES.map((c) => round(Number(s[`${c.key}_kg`]))),
        s.other_label ?? '',
        round(Number(s.total_kg)),
        s.delivered_by_name,
        s.vehicle_number,
      ]),
    ],
    [14, 30, 30, 18, 18, 12, 16, 12, 12, 13, 11, 11, 22, 12, 20, 14],
  )

  XLSX.writeFile(wb, `${meta.fileStem}.xlsx`, { compression: true })
}
